### ISSUE TITLE
[BUG] Source Link does not appear to work as expected

### ISSUE THREAD

**Issue by rheone** [sandialabs/Gulliver#16]
Source is not available in Visual Studio 2019 community edition.

**Comment by rheone** [comment]
This may be a side effect of the way the nuget packages were originally built and released, and may have resolved itself now that we have an appropriate GitHub hash associated. 

Verify, but note to self don't pack from internal repository

**Comment by rheone** [comment]
This issue seems to be resolved, and should be covered in the next release by our current build pipeline.

**Comment by ahsteele** [comment]
Any reason not to release to make the issue go away?

**Comment by rheone** [comment]
I see no issue with a patch change release once we include the current PRs
