### ISSUE TITLE
[Doc] Pull request numbering looks bad when making an actual pull request

### ISSUE THREAD

**Issue by ahsteele** [sandialabs/Gulliver#36]
# Description 

Markdown 1. numbering fails when actually making the PR.
![image](https://user-images.githubusercontent.com/428747/68550611-89947200-03c1-11ea-83b4-ce07be91ba9d.png)

# Impact 

Looks stupid

# Proposed solutions

While not conveneient when reordering markdown will respect human numbered lists:
> 1.
> 2.
> 3.

etc.

# Can you help?

I can

**Comment by rheone** [comment]
@ahsteele looking at the [preview](https://github.com/sandialabs/Gulliver/blob/master/.github/pull_request_template.md) it appears appropriate. Did you fix it w/o assigning the issue, or is it rendering differently when a PR is actually made?

**Comment by ahsteele** [comment]
It doesn't redner anything when a PR is made. So you get a raw MD w/ the 1. as in the screenshot.
