### ISSUE TITLE
[Bug] Releasing to NuGet from Azure DevOps fails

### ISSUE THREAD

**Issue by ahsteele** [sandialabs/Gulliver#38]
# Describe the bug

When going through the release process the .snupkg file fails to upload to NuGet

# Expected behavior

I expect to be able to deploy w/o issue.

# Example of how to Reproduce

See my most recent release from Azure DevOps: https://dev.azure.com/sandianationallabs/Gulliver/_releaseProgress?_a=release-pipeline-progress&releaseId=1

**Comment by rheone** [comment]
The theory is that a never version of NuGet may fix this issue, but I don't know where @nicksterx got with this. For whatever reason `.snupkg` aren't handled well, even by the GitHub actions.

**Comment by ahsteele** [comment]
I think this is now related to #41 and can probably be tied to the fix there. Does that make sense to you @nicksterx?

**Comment by nicksterx** [comment]
Yeah that makes sense

**Comment by nicksterx** [comment]
This has been resolved.
